# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb16ad9143be272098fc130f18bc73f834ae4c3be5880e297f8921328ed3dac6cc294f1543137eb659945a97bbe88f75036507c82f57eaed6d1c21212a447a55

test:
  secret_key_base: d963e61ff1cb494a1b673e830721af1955107b2aeb8fbfc46631ff37e9f23f6542cdb10f809e424330ac8b591468e09ac2cbcac8a6bec0049d8dacbce3a38aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
